[pytest]
# Minimum version of pytest required
minversion = 8.0

DJANGO_SETTINGS_MODULE = finance_app.settings.base
python_files = tests.py test_*.py *_tests.py
pythonpath = .

# Default command-line arguments to always apply when running 'pytest'
addopts = 
    --strict-markers
    --strict-config
    -ra
    -v
    --cov=finance_app
    --cov=accounts
    --cov-report=term-missing
    --hypothesis-show-statistics

# Directories where pytest should look for tests
testpaths =
    tests

# Register custom markers to avoid typos (example)
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
